Import(['env'])
env = env.Clone()

# To include new files just add to the list, or Glob("*.cs")
sources = Glob("src/*.cs")

env['CSC_LIBS'] = [
    "System.Windows.Forms.dll",
    "System.Drawing.dll"
]

objname = env.GetDirectoryName([])
env.CLIProgram(objname, sources)
