Import(['env'])
env = env.Clone()

# To include new files just add to the list, or Glob("*.cs")
sources = Glob("src/*.cs")

env['CSC_SEARCH'] = [
    "projects/Injector/lib",
    "projects/Injector/runlib"
]

env['CSC_LIBS'] = env['CSC_RUN'] = [
    "Mono.Cecil.dll"
]

objname = env.GetDirectoryName([])
env.CLIProgram(objname, sources)
